---
layout: cv
title: Ruby Higdon
---

<div id="webaddress">
<a href="ruby.blu.higdon@gmail.com">ruby.blu.higdon@gmail.com</a>
| <a href="www.linkedin.com/in/rubyhigdon">www.linkedin.com/in/rubyhigdon</a>
</div>


## Experience

### Student Writer
*Brigham Young University-Idaho | September 2022 - Present*

- Lead data analyst for Freshman Merit Scholarship reconstruction
- Analyzed LDS Philanthropies reports and worked closely with large donors to the university
- Edited professional documents daily through Microsoft Office and Adobe Acrobat

### Technology Specialist
*The Church of Jesus Christ of Latter-day Saints | March 2022 - July 2022*

- Designed trainings for groups of over 200 missionaries on how to effectively use social media
- Produced, filmed, and edited high-quality audio and video content
- Managed ad campaigns for two Facebook pages with a combined budget of $1,300

### Editor-in-Chief
*Mountainside High School | January 2020 - May 2020*

- Launched first student-run newspaper
- Directed each class period and all major decisions regarding the newspaper
- Wrote articles for the publication and served as the main editor of each article

## Education

### Bachelor's Degree in Data Science
*Brigham Young University-Idaho | Anticipated July 2025*

- Coursework in Python, HTML, SQL, and R
- 4.0 GPA

### English Education Major Coursework 
*Brigham Young University | August 2020 - January 2021*

- Dual Language Immersion Teaching Minor
- 4.0 GPA

## Additional Relevant Information

### Missionary Service 
*New Mexico Albuquerque Mission | February 2021 - July 2022*

- Served a full-time Spanish-speaking mission for the Church of Jesus Christ of Latter-day Saints
- Trained missionaries and members of local congregations as a Social Media Specialist

### Spanish Language
- Earned Seal of Biliteracy in the state of Oregon
- Seven years in Spanish immersion from K-6, three years of advanced-level high school courses, and  two colleges classes
- Taught in Spanish-speaking congregations throughout missionary service


<!-- ### Footer

Last updated: May 2013 -->